config/routes.rb
Compliance::Application.routes.draw do
  get "sessions/new"

  root 'tasks#index'
  

  get 'signup' => 'users#new', as: :signup
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"

  post "task/:id/subscribe" => "tasks#subscribe", :as => "subscribe"
  delete "task/:id/subscriber/:user_id" => "tasks#unsubscribe", :as => "unsubscribe"
 
  resources :users
  resources :sessions
  
  resources :tasks do
    resources :versions
    collection do
      get 'filter'
      get 'export'
    end
  end

  

end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/task.rb
class Task < ActiveRecord::Base
 
  resourcify
  has_paper_trail
  
  validates :agency, :facility, :due_date, presence: true
  validates_date :completed_date, allow_nil: true, :on_or_before => lambda { Date.current }

  default_scope -> { order('due_date') }

  def self.filter(params, user = nil)
    result = self.all
    params.each do |field, criteria|
      if field.match(/due_date|completed_date/) && criteria.present?
        result = result.where("DATE(#{field}) = ?", criteria)
      end
    end

    if params['owner'] && user
      result = result.with_role(:owner, user)
    end

    result
  end
  
  def self.to_csv(params)
    tasks = params.nil? ? self.all : self.filter(params)
    CSV.generate do |csv|
      csv << (column_names << 'owner')
      tasks.each do |task|
        csv << (task.attributes.values << task.owner.full_name_reversed)
      end
    end
  end

  def owner
    User.with_role(:owner, self).first
  end

  def owner=(user)
    self.owner.remove_role(:owner, self) if User.with_role(:owner, self).count > 0
    user.add_role(:owner, self)
  end

  def subscribers
    User.with_role(:subscriber, self)
  end

  def subscribers=(users = [])

    subscribers.each do |subscriber|
      subscriber.remove_role :subscriber, self
    end
    
    users.each do |user|
      User.find(user).add_role :subscriber, self
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  authenticates_with_sorcery!
  
  validates :username, :user_first_name, :user_last_name, :email, presence: true
  validates_uniqueness_of :username

  def full_name_reversed
    "#{user_last_name}, #{user_first_name}"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include Pundit
  protect_from_forgery with: :exception

  before_action :require_login

  rescue_from Pundit::NotAuthorizedError, with: :not_authorized
    
  private

  def not_authenticated
    redirect_to login_path, alert: "Log in to view this page."
  end

  def not_authorized
    flash[:error] = "You are not authorized to perform this action."
    redirect_to request.headers["Referer"] || root_path
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login
  
  def new
  end
  
  def create
    user = login(params[:username], params[:password])
    if user
      redirect_to root_url, notice: "Logged in."
    else
      redirect_to new_session_path, alert: "Username or password was invalid."
    end
  end
  
  def destroy
    logout
    redirect_to login_path, notice: "Logged out."
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  
  def export
    respond_to do |format|
      format.html
      format.csv { render text: Task.to_csv(params[:filter]) }
    end
  end
  
  def filter 
    @tasks = Task.filter(params['filter'], current_user)
    @tasks = @tasks.page(params[:page])
    render 'index'
  end

  def index
    @tasks = Task.page(params[:page])
  end

  def show
    @task = Task.find(params[:id])
    authorize @task
  end

  def new
    @task = Task.new
    authorize @task
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    authorize @task
    if @task.update(task_params)
      @task.owner = User.find(params[:role]['owner'])
      flash[:notice] = 'Record updated successfully.'
      redirect_to task_path(@task) 
    else
      flash.now.alert = 'Update invalid. Record not saved.'
      render 'edit'
    end
  end

  def create
    @task = Task.new(task_params)
    authorize @task
    if @task.save
      @task.owner = User.find(params[:role]['owner'])
      flash[:notice] = 'Record saved successfully.'
      redirect_to tasks_path
    else
      flash.now.alert = 'Data invalid. Record not saved.'
      render 'new'
    end
  end

  def destroy
    @task = Task.find(params[:id])
    authorize @task
    @task.destroy
    redirect_to tasks_path
  end

  def subscribe
    @task = Task.find(params[:id])
    User.find(params[:role]['subscriber']).add_role :subscriber, @task
    redirect_to edit_task_path(@task)  
  end

  def unsubscribe
    @task = Task.find(params[:id])
    User.find(params[:user_id]).remove_role :subscriber, @task
    redirect_to edit_task_path(@task)
  end

  private

    def task_params
      params.require(:task).permit!
    end
      
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  skip_before_action :require_login
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      @user.add_role(:editor, Task) if params[:editor] == "true"
      redirect_to login_path, notice: "Signed up."
    else
      render :new
    end
  end
  
  private
    def user_params
      params.require(:user).permit!
    end
end

app/controllers/versions_controller.rb
class VersionsController < ApplicationController

  def index
    @task = Task.find(params[:task_id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
  def csv_params(params)
    if params.nil?
      { format: 'csv' }
    else
      { format: 'csv' }.merge({ filter: params }) unless params.nil?
      end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Compliance</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= logged_in? ? link_to("Log Out", logout_path) : link_to("Log In", login_path)%>

<%= current_user.username if current_user %>

<% flash.each do |name, message| %>
  <%= content_tag :div, message, id: "flash_#{name}" %>
<% end %>
  
<%= yield %>

</body>
</html>

app/views/tasks/_form.html.haml
= form_for @task do |f|
  %p
    = f.label :facility
    %br
    = f.text_field :facility
  %p
    = f.label :agency
    %br
    = f.text_field :agency
  %p
    = f.label :description
    %br
    = f.text_area :description
  %p
    = f.label :due_date
    %br
    = f.date_select :due_date
  %p
    = f.label :completed_date
    %br
    = f.date_select :completed_date
  %p
    = label_tag "Owner"
    %br
    - if @task.new_record?
      = collection_select(:role, :owner, User.all, :id, :full_name_reversed)
    - else
      = collection_select(:role, :owner, User.all, :id, :full_name_reversed,  { :selected => User.with_role(:owner, @task).first.id })
  %p
    = f.submit 'Submit'

- if !@task.new_record?
  %p Subscribers
  = form_tag({ controller: "tasks", action: "subscribe", id: @task.id }, method: "post") do
    = collection_select(:role, :subscriber, User.all, :id, :full_name_reversed)
    = submit_tag "Add"

  %ul
    - @task.subscribers.each do |subscriber|
      %li
        = subscriber.full_name_reversed
        = link_to "Delete", unsubscribe_path(@task, subscriber), method: :delete 

app/views/tasks/edit.html.haml
= render 'form'

app/views/tasks/index.html.haml
%h1 'All Tasks'

%div
  = form_tag("/tasks/filter", method: "get") do
    = label_tag('filter[due_date]', 'Filter By Due Date')
    = text_field_tag('filter[due_date]')
    = label_tag('filter[completed_date]', 'Filter By Completed Date')
    = text_field_tag('filter[completed_date]')
    = label_tag('filter[owner]', 'Only Tasks I Own')
    = check_box_tag('filter[owner]')
    = submit_tag("Filter Results")
    
%table
  %thead
    %tr
      %td Owner
      %td Agency
      %td Facility
      %td Description
      %td
      - if current_user.has_role?(:editor, Task)
        %td
  %tbody
    - @tasks.each do |task|
      %tr
        %td= User.with_role(:owner, task).first.full_name_reversed
        %td= task.agency
        %td= task.facility
        %td= task.description
        - if policy(task).update?
          %td= link_to 'Edit', edit_task_path(task)
        - else
          %td= link_to 'View', task_path(task)
        - if current_user.has_role?(:editor, Task)
          %td= link_to 'Delete', task_path(task), method: :delete

%br
= paginate @tasks

%br
= link_to 'New Task', new_task_path
= link_to 'Export Tasks', export_tasks_path(csv_params(params['filter']))

app/views/tasks/new.html.haml
= render 'form'

app/views/tasks/show.html.haml
%ul
  - @task.attributes.each do |attribute|
    %li
      = "#{attribute[0]}: #{attribute[1]}"
  %li
    = "Owner: #{User.with_role(:owner, @task).first.full_name_reversed}"
%h3 Subscribers
%ul
  - @task.subscribers.each do |subscriber|
    %li
      = subscriber.full_name_reversed

= link_to "Audit Trail", task_versions_path(@task)
= link_to "Task List", tasks_path

app/views/users/new.html.haml
%h1 Sign Up

= form_for @user do |f|
  %p
    = f.label :username
    %br
    = f.text_field :username
  %p
    = f.label :email
    %br
    = f.text_field :email
  %p
    = f.label :user_first_name, 'First Name'
    %br
    = f.text_field :user_first_name
  %p
    = f.label :user_last_name, 'Last Name'
    %br
    = f.text_field :user_last_name
  %p
    = f.label :password
    %br
    = f.password_field :password
  %p
    = label_tag "Editor"
    = check_box_tag "editor", "true"
  %p
    = f.submit 'Sign Up'

app/views/versions/index.html.haml
%table
  %thead
    %tr
      %td Agency
      %td Facility 
      %td Description
      %td Due Date
      %td Completed Date
      %td Changed By User 
      %td Change Date
  %tbody
    - @task.versions.each do |version|
      %tr
        %td= version.reify.agency
        %td= version.reify.facility
        %td= version.reify.description
        %td= version.reify.due_date
        %td= version.reify.completed_date
        %td= User.find(version.whodunnit).full_name_reversed
        %td= version.created_at
    %tr
      %td= @task.agency
      %td= @task.facility
      %td= @task.description
      %td= @task.due_date
      %td= @task.completed_date
      %td N/A
      %td N/A 